#!/bin/sh /etc/rc.common

NAME=piratebox
START=80
STOP=20
EXTRA_COMMANDS="setup init nodns updatePB mountPB init_openwrt stop_keep  timesave"
EXTRA_HELP="	setup	Activate current USB and network configuration
	init			initialize installation
	init_openwrt  rerun startup-openwrt initializarion from piratebox scripts (caution)
	updatePB  Updates only PirateBox files from USB stick Image-File
	nodns	Disable local DNS redirection through dnsmasq
	stop_keep  stops current running deamons and leaves /opt/piratebox mounted
	timesave   Installs timesafe script into rc.local and enables cron"


# include PirateBox shared functionality
###  at this case, I assume it is installed in /usr/local as opkg destination

if [ -e /etc/ext.config ] ; then 
  . /etc/ext.config
  . $ext_linktarget/usr/share/piratebox/piratebox.common
else
  . /usr/share/piratebox/piratebox.common
fi

setup() {
  pb_setup
}

init() {
  pb_init
}

init_openwrt() {
   pb_init_image

}

nodns() {
  pb_nodns
}

updatePB () {
  pb_updatePBImage
}

mountPB () {
   pb_mount pb
}

start() {
  if [ ! -d "$pb_usbdir" ]
  then
	echo "It seems PirateBox was not initialized correctly"
	echo " or the USB stick is not mounted"
	exit 99
  fi
  pb_start 
}

stop() {
  pb_stop
}

stop_keep() {
	pb_stop_and_keep
}

timesave() {
        . $ext_linktarget/usr/share/piratebox/timesave.common
	pb_install_timesave $pb_piratebox_conf $pb_timesave_script
}


